### ISSUE TITLE
Aanmaken nieuw profiel

### ISSUE THREAD

**Issue by joroelev** [praegus/MotorsportsManager#11]
### Description
Als speler wil ik een profiel kunnen aanmaken zodat ik een seizoen kan starten

Binnen dit profiel moet als eerste worden opgenomen:
- profiel naam

### Acceptatie criteria

- [x] profiel naam moet uniek zijn 
    - [x] hoofdletter ongevoelig
- [x] profiel naam moet voldoen aan:
    - [x] lengte 1 tot 10 karakters
    - [x] geen speciale tekens(alpha numeriek)
- [x] Profiel naam moet ingevoerd kunnen worden
- [x] Het moet zichtbaar zijn welk profiel actief

### Tasks

Frontend:
- [x] inlogpagina maken
- [x] form met profielnaam posten
- [x] tonen actief profiel, nieuw component en routing.
- [x] error handling

Backend:

- [x] create endpoint maken en opslaan profiel
- [x] error handling uniek profielnaam (code 409)
- [x] error handling invoer validatie
