### ISSUE TITLE
Ga verder met bestaand profiel

### ISSUE THREAD

**Issue by jrijnaars** [praegus/MotorsportsManager#12]
### Description
Als speler wil ik met mijn bekende profiel kunnen activeren, zodat mijn bekende profiel actief word

### Acceptatiecriteria

- [x] kunnen activeren van een bestaand profiel
- [ ] kunnen zien dat mijn gekozen profiel actief is

### Tasks
Frontend:
- [x] voeg form toe om bestaand profiel te activeren
- [x] error handling
- [x] routing naar profielpagina

Backend:

- [x] maak get endpoint
    - [x] hoofdletter ongevoelig
- [x] error indien het opgevraagde profiel niet bestaat (404)
