### ISSUE TITLE
Race Tutorial

### ISSUE THREAD

**Issue by jrijnaars** [praegus/MotorsportsManager#13]
Tutorial rac

Uitbreiden van track info:
"trackInfo": [
                {
                    "name": "TUTORIAL",
                    "status": "COMPLETED",
			  "result": {
				"position": 3
			  }
                },
		    {
                    "name": "ROCKY_ROAD",
                    "status": "UPCOMING"
                }
            ]

Post call om race te rijden:

POST seasons/2024-2025/races/TUTORIAL
{ "name": "Fin" }

geeft race verslag terug:
{
 "message": "blah blah"
}

Standaard messages:
1: Congratulations you won the match!
2: ..
3: Congratulations you reached the podium and won 10.000 euros!
4. ...

Frontend popup met twee teksten:
bovenaan het race verslag
daaronder de standaard message (je wordt vast 3e)

(zouden meerdere pagina's kunnen zijn, niet hard gespecificeerd). 
Als je de popup sluit is je geld bijgewerkt, en je next track geupdate naar de volgende track.

Onder Season komt een extra blok te staan met Completed Tracks:
Hier komt de naam van de track + je positie te staan

### Acceptatie criteria

- [ ] Als je op Race klikt wordt je 3e en krijg je 10000 euro
- [ ] Race informatie wordt via een popup getoond
- [ ] De afgeronde races zie je terug op je profiel

### Tasks
Frontend:
- [ ]

Backend:
- [ ]
