### ISSUE TITLE
Start een nieuw seizoen

### ISSUE THREAD

**Issue by jrijnaars** [praegus/MotorsportsManager#15]
### Description
Als speler wil ik me voor een nieuw seizoen kunnen inschrijven, zodat ik kan beginnen met het spelen van dit seizoen.

### Acceptatie criteria

- [ ] inschrijfgeld moet afgaan van het organisatie budget
- [ ] inschrijfgeld is je budget voor het seizoen
- [ ] je krijgt een basis model auto
- [ ] team naam word gecreëerd 
- [ ] team word zichtbaar bij organisatie
- [ ] mag alleen als je nog niet met een gelijk seizoen bezig bent

### Tasks
Frontend:
- [ ]

Backend:
- [ ]
