### ISSUE TITLE
Toon eerste 2 races

### ISSUE THREAD

**Issue by jrijnaars** [praegus/MotorsportsManager#37]
### Description
Als een speler wil ik de details van de komende 2 races kunnen inzien. zodat ik me kan voorbereiden op deze races

### Acceptatie criteria

- [ ] 2 races moeten vooruit getoond worden
- [ ] details als korte bochten, lange bochten, lange stukken moeten zichtbaar zijn

### Tasks
Frontend:
- [ ] toon de komende 2 circuits

Backend:
- [ ]
