### ISSUE TITLE
Koop betere banden

### ISSUE THREAD

**Issue by jrijnaars** [praegus/MotorsportsManager#38]
### Description
Als een speler wil ik beter banden kunnen kopen. Zodat de performance van mn go-kart erop vooruit gaat

### Acceptatie criteria

- [ ] verschillende banden types moeten te kiezen zijn.
- [ ] de performance toename moet zichtbaar zijn
- [ ] de investering moet van het seizoens budget afgehaald worden 

### Tasks
Frontend:
- [ ] maak bla
- [ ] kwgeh
- [ ] 

Backend:
- [ ]
