### ISSUE TITLE
Koop een beter chassis

### ISSUE THREAD

**Issue by jrijnaars** [praegus/MotorsportsManager#39]
### Description
Als speler wil ik een beter chassis kunnen kopen, zodat de performance van mijn go-kart toeneemt

### Acceptatie criteria

- [ ] verschillende chassis moeten te kiezen zijn
- [ ] de toename in performance moet zichtbaar zijn
- [ ] de investering moet van het seizoens budget afgehaald worden.

### Tasks
Frontend:
- [ ]

Backend:
- [ ]
